# A GNU Makefile to build the docs

# Note: This makefile include remake-style target comments.
# These comments before the targets start with #:

.PHONY: latex

all: latex

#: Forward the call to tex, Whatever it is you want to do
%:
	$(MAKE) -C tex $@
