(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[BesselJ[1,a_.+b_.*x_],x_Symbol] :=
  -BesselJ[0,a+b*x]/b /;
FreeQ[{a,b},x]


(* ::Code:: *)
Int[BesselJ[n_,a_.+b_.*x_],x_Symbol] :=
  -2*BesselJ[n-1,a+b*x]/b + Int[BesselJ[n-2,a+b*x],x] /;
FreeQ[{a,b},x] && IGtQ[(n-1)/2,0]


(* ::Code:: *)
(* Int[BesselJ[n_,a_.+b_.*x_],x_Symbol] :=
  (-1)^n*Int[BesselJ[-n,a+b*x],x] /;
FreeQ[{a,b},x] && ILtQ[n,0] *)


(* ::Code:: *)
Int[BesselJ[n_,a_.+b_.*x_],x_Symbol] :=
  (a+b*x)^(n+1)*HypergeometricPFQ[{(n+1)/2},{(n+3)/2,n+1},-1/4*(a+b*x)^2]/(2^n*b*Gamma[n+2]) /;
FreeQ[{a,b,n},x]



