.de Vb \" (V)erbatim (b)egin.  Use fixed width font and no justification
.ft CW
.nf
..
.de Ve \" (V)erbatim (e)nd.  Return to regular font and justification
.ft R
.fi
..
.\" --------------------------------------------------------------------
.TH MATHICS 1 "11 August 2012" "Mathics"
.SH NAME
mathics \- A general-purpose computer algebra system.
.SH SYNOPSIS
\fBmathics\fP [\fIoptions\fP]... [\fIfile\fP]
.SH DESCRIPTION
Mathics is a general-purpose computer algebra system (CAS). It is meant
to be a free, light-weight alternative to Mathematica.
.SH DOCUMENTATION
The primary documentation for Mathics is a PDF document that should have
come with your installation. If not, documentation can be found online 
at <http://www.mathics.org>.
.SH SUPPORT
If you need help with Mathics try asking on either the mathics IRC 
channel ('mathics ' on Freenode), or the mathics-users google groups
page <mathic-users_URL>. Please be respectful and remember that unlike 
commercial software, no one is being paid to help you.
.SH BUGS
Please report any bugs you find by opening an issue on the mathics 
github page <http://www.github.com/poeschko/mathics/issues>.
.SH AUTHOR
Jan Pöschko <jan@poeschko.com>
