# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-11 13:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('query', models.TextField()),
                ('result', models.TextField(null=True)),
                ('timeout', models.BooleanField()),
                ('out', models.TextField()),
                ('error', models.BooleanField()),
                ('remote_user', models.CharField(max_length=255, null=True)),
                ('remote_addr', models.TextField(null=True)),
                ('remote_host', models.TextField(null=True)),
                ('browser', models.TextField(null=True)),
                ('meta', models.TextField(null=True)),
                ('log', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worksheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('content', models.TextField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='worksheets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='worksheet',
            unique_together=set([('user', 'name')]),
        ),
    ]
