(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



BeginPackage["QuantumGroups`Representations`",{"QuantumGroups`","QuantumGroups`RootSystems`","QuantumGroups`Algebra`","QuantumGroups`WeylGroups`","QuantumGroups`LittelmannPaths`","QuantumGroups`Steinberg`","QuantumGroups`Utilities`Debugging`"}];


WeightMultiplicities::usage="";


WeightMultiplicity::usage="";


DecomposeRepresentation::usage="";


Weights::usage="";


WeightDiameter::usage="";


PositiveWeights::usage="";


qDimension::usage="";


MultiplicityFreeQ::usage="MultiplicityFreeQ[\[CapitalGamma],V] determines whether every weight space in the representation V of \[CapitalGamma] has dimension 1. In the case that this is false, MultiplicityFreeQ is much faster than WeightMultiplicities[\[CapitalGamma],V].";


DualRepresentation;


Begin["`Private`"];


DualRepresentation[X_DirectSum]:=DualRepresentation/@X
DualRepresentation[X_TensorProduct]:=DualRepresentation/@(Reverse[X])
DualRepresentation[Irrep[\[CapitalGamma]_][V_]]:=Irrep[\[CapitalGamma]][-LongestWord[\[CapitalGamma]].V]


q=Global`q;


WeightMultiplicities[\[CapitalGamma]_,\[DoubleStruckCapitalC]]:={{ZeroVector[Rank[\[CapitalGamma]]],1}}


WeightMultiplicities[\[CapitalGamma]_,TensorProduct[V_]]:=WeightMultiplicities[\[CapitalGamma],V]


WeightMultiplicities[\[CapitalGamma]_,Irrep[\[CapitalGamma]_][\[Lambda]_]]:=WeightMultiplicities[\[CapitalGamma],Irrep[\[CapitalGamma]][\[Lambda]]]=LittelmannPathWeightMultiplicities[\[CapitalGamma],Irrep[\[CapitalGamma]][\[Lambda]]]


DecomposeRepresentation[\[CapitalGamma]_][Irrep[\[CapitalGamma]_][\[Lambda]_]\[CircleTimes]Irrep[\[CapitalGamma]_][\[Mu]_]]:=DecomposeRepresentation[\[CapitalGamma]][Irrep[\[CapitalGamma]][\[Lambda]]\[CircleTimes]Irrep[\[CapitalGamma]][\[Mu]]]=LittelmannPathDecomposeRepresentation[\[CapitalGamma]][Irrep[\[CapitalGamma]][\[Lambda]]\[CircleTimes]Irrep[\[CapitalGamma]][\[Mu]]]


Weights[\[CapitalGamma]_,V_]:=Weights[\[CapitalGamma],V]=First/@WeightMultiplicities[\[CapitalGamma],V]


WeightMultiplicity[\[CapitalGamma]_,V_,\[Mu]_]:=WeightMultiplicity[\[CapitalGamma],V,\[Mu]]=Plus@@Cases[WeightMultiplicities[\[CapitalGamma],V],{\[Mu],n_}:>n]


WeightDiameter[\[CapitalGamma]_,V_]:=WeightDiameter[\[CapitalGamma],V]=2Max[Sqrt[KillingForm[\[CapitalGamma]][#,#]]&/@Weights[\[CapitalGamma],V]]


DecomposeRepresentation[\[CapitalGamma]_][Irrep[\[CapitalGamma]_][\[Lambda]_]]:=Irrep[\[CapitalGamma]][\[Lambda]]


DecomposeRepresentation[\[CapitalGamma]_][V_DirectSum]:=SortWeights[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]]/@V]


DecomposeRepresentation[\[CapitalGamma]_][V_DirectSum\[CircleTimes]W_]:=SortWeights[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]][Distribute[V\[CircleTimes]W,DirectSum]]]


DecomposeRepresentation[\[CapitalGamma]_][V_\[CircleTimes]W_DirectSum]:=SortWeights[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]][Distribute[V\[CircleTimes]W,DirectSum]]]


DecomposeRepresentation[\[CapitalGamma]_][(U_\[CircleTimes]V_)\[CircleTimes]W__]:=SortWeights[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]][U\[CircleTimes]V]\[CircleTimes]W]]


DecomposeRepresentation[\[CapitalGamma]_][U_\[CircleTimes](V_\[CircleTimes]W__)]:=SortWeights[\[CapitalGamma]][DecomposeRepresentation[\[CapitalGamma]][U\[CircleTimes]DecomposeRepresentation[\[CapitalGamma]][V\[CircleTimes]W]]]


HighestWeight[\[CapitalGamma]_,Irrep[\[CapitalGamma]_][\[Lambda]_]]:=\[Lambda]


WeightMultiplicities[\[CapitalGamma]_,V_]/;MinisculeRepresentationQ[\[CapitalGamma],V]:=WeightMultiplicities[\[CapitalGamma],V]={#,1}&/@SortWeights[\[CapitalGamma]][WeylOrbit[\[CapitalGamma],HighestWeight[\[CapitalGamma],V]]]


WeightMultiplicities[\[CapitalGamma]_,Irrep[\[CapitalGamma]_][\[Mu]_]]/;ZeroVectorQ[\[Mu]]:={{ZeroVector[Rank[\[CapitalGamma]]],1}}


TensorWeightMultiplicities[{\[Lambda]_,a_},{\[Mu]_,b_}]:={\[Lambda]+\[Mu],a b}


CombineWeightMultiplicities[\[CapitalGamma]_,l_]:={#[[1,1]],Plus@@(Last/@#)}&/@Split[SortWeightMultiplicities[\[CapitalGamma]][l],#1[[1]]==#2[[1]]&]


WeightMultiplicities[\[CapitalGamma]_,V_\[CircleTimes]W_]:=WeightMultiplicities[\[CapitalGamma],V\[CircleTimes]W]=CombineWeightMultiplicities[\[CapitalGamma],Flatten[Outer[TensorWeightMultiplicities,WeightMultiplicities[\[CapitalGamma],W],WeightMultiplicities[\[CapitalGamma],V],1],1]]


WeightMultiplicities[\[CapitalGamma]_,V_DirectSum]:=WeightMultiplicities[\[CapitalGamma],V]=CombineWeightMultiplicities[\[CapitalGamma],Join@@(WeightMultiplicities[\[CapitalGamma],#]&/@(List@@V))]


WeightMultiplicity[\[CapitalGamma]_,V_DirectSum,\[Lambda]_]:=Plus@@(WeightMultiplicity[\[CapitalGamma],#,\[Lambda]]&/@(List@@V))


PositiveWeights[\[CapitalGamma]_,V_]:=PositiveWeights[\[CapitalGamma],V]=Select[Weights[\[CapitalGamma],V],PositiveWeightQ[\[CapitalGamma]]]


qDimension[\[CapitalGamma]_][V_]:=qDimension[\[CapitalGamma]][V]=With[{\[Rho]=Table[1,{Rank[\[CapitalGamma]]}]},Plus@@(WeightMultiplicities[\[CapitalGamma],V]/.{\[Lambda]_,n_Integer}:>n q^KillingForm[\[CapitalGamma]][2\[Rho],\[Lambda]])]


fastQDimension[Subscript[(\[CapitalGamma]:(A|D|E)), n_]][Irrep[Subscript[\[CapitalGamma]_, n_]][\[Lambda]:{___Integer}]]:=fastQDimension[Subscript[\[CapitalGamma], n]][Irrep[Subscript[\[CapitalGamma], n]][\[Lambda]]]=
Module[{
exp=KillingForm[Subscript[\[CapitalGamma], n]][2Table[1,{n}],\[Lambda]],
sum=0,
latestLowerings={LittelmannPath[Subscript[\[CapitalGamma], n]][{\[Lambda]}]}
},
DebugPrint["Running fastQDimensions, ",Irrep[Subscript[\[CapitalGamma], n]][\[Lambda]]];
While[exp>=0,
DebugPrint["... exp=",exp];
sum+=q^exp Length[latestLowerings];
exp-=2;
latestLowerings=LittelmannPathOneStepLowerings[latestLowerings];
];
Expand[sum+(sum/.{q->q^-1})-(sum/.{q->0})]
]


(* this could be optimised more, by staying in the positive half-space *)
fastQDimension[Subscript[(\[CapitalGamma]:(B|C|F|G)), n_]][Irrep[Subscript[\[CapitalGamma]_, n_]][\[Lambda]:{___Integer}]]:=fastQDimension[Subscript[\[CapitalGamma], n]][Irrep[Subscript[\[CapitalGamma], n]][\[Lambda]]]=
Module[{
\[Rho]=Table[1,{n}],
sum=0,
latestLowerings={LittelmannPath[Subscript[\[CapitalGamma], n]][{\[Lambda]}]}
},
While[Length[latestLowerings]>0,
sum+=Plus@@(q^KillingForm[Subscript[\[CapitalGamma], n]][2\[Rho],LittelmannPathEndpoint[#]]&/@latestLowerings);
latestLowerings=LittelmannPathOneStepLowerings[latestLowerings];
];
sum
]


qDimension[\[CapitalGamma]_][V:Irrep[\[CapitalGamma]_][\[Lambda]_]]:=recursiveQDimension[\[CapitalGamma]][V]


qDimension[\[CapitalGamma]_][V_\[CircleTimes]W_]:=Expand[qDimension[\[CapitalGamma]][V]qDimension[\[CapitalGamma]][W]]
qDimension[\[CapitalGamma]_][V_\[CirclePlus]W_]:=Expand[qDimension[\[CapitalGamma]][V]+qDimension[\[CapitalGamma]][W]]


recursiveQDimension[\[CapitalGamma]_][V_\[CircleTimes]W_]:=Expand[recursiveQDimension[\[CapitalGamma]][V]recursiveQDimension[\[CapitalGamma]][W]]
recursiveQDimension[\[CapitalGamma]_][V_DirectSum]:=Expand[Plus@@(recursiveQDimension[\[CapitalGamma]]/@V)]


recursiveQDimension[\[CapitalGamma]_][V:Irrep[\[CapitalGamma]_][\[Lambda]_]]:=recursiveQDimension[\[CapitalGamma]][V]=Module[{t,k,u},
If[ZeroVectorQ[\[Lambda]],Return[1]];
If[UnitVectorQ[\[Lambda]], Return[fastQDimension[\[CapitalGamma]][V]]];
k=Position[\[Lambda],m_/;m>0][[1,1]];
u=UnitVector[Rank[\[CapitalGamma]],k];
t=Irrep[\[CapitalGamma]][\[Lambda]-u]\[CircleTimes]Irrep[\[CapitalGamma]][u];
Expand[recursiveQDimension[\[CapitalGamma]][t]-recursiveQDimension[\[CapitalGamma]][DeleteCases[DecomposeRepresentation[\[CapitalGamma]][t],V]]]
]


fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{0,0,0,0,0,1}]]=3+1/q^16+1/q^14+1/q^12+1/q^10+2/q^8+2/q^6+2/q^4+2/q^2+2 q^2+2 q^4+2 q^6+2 q^8+q^10+q^12+q^14+q^16;fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{0,0,0,0,1,0}]]=23+1/q^30+1/q^28+2/q^26+3/q^24+5/q^22+6/q^20+8/q^18+10/q^16+13/q^14+14/q^12+17/q^10+19/q^8+21/q^6+21/q^4+23/q^2+23 q^2+21 q^4+21 q^6+19 q^8+17 q^10+14 q^12+13 q^14+10 q^16+8 q^18+6 q^20+5 q^22+3 q^24+2 q^26+q^28+q^30;fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{0,0,0,1,0,0}]]=161+1/q^42+1/q^40+3/q^38+5/q^36+8/q^34+11/q^32+18/q^30+23/q^28+32/q^26+41/q^24+53/q^22+63/q^20+78/q^18+89/q^16+105/q^14+116/q^12+130/q^10+139/q^8+151/q^6+154/q^4+161/q^2+161 q^2+154 q^4+151 q^6+139 q^8+130 q^10+116 q^12+105 q^14+89 q^16+78 q^18+63 q^20+53 q^22+41 q^24+32 q^26+23 q^28+18 q^30+11 q^32+8 q^34+5 q^36+3 q^38+q^40+q^42;

fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{0, 0, 1, 0, 0, 0}]] = 
    23 + q^(-30) + q^(-28) + 2/q^26 + 3/q^24 + 5/q^22 + 6/q^20 + 8/q^18 + 10/q^16 + 13/q^14 + 
     14/q^12 + 17/q^10 + 19/q^8 + 21/q^6 + 21/q^4 + 23/q^2 + 23*q^2 + 21*q^4 + 21*q^6 + 19*q^8 + 
     17*q^10 + 14*q^12 + 13*q^14 + 10*q^16 + 8*q^18 + 6*q^20 + 5*q^22 + 3*q^24 + 2*q^26 + q^28 + 
     q^30;
 
fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{0, 1, 0, 0, 0, 0}]] = 
    6 + q^(-22) + q^(-20) + q^(-18) + 2/q^16 + 3/q^14 + 3/q^12 + 4/q^10 + 5/q^8 + 5/q^6 + 
     5/q^4 + 6/q^2 + 6*q^2 + 5*q^4 + 5*q^6 + 5*q^8 + 4*q^10 + 3*q^12 + 3*q^14 + 2*q^16 + q^18 + 
     q^20 + q^22;
 
fastQDimension[Subscript[E, 6]][Irrep[Subscript[E, 6]][{1, 0, 0, 0, 0, 0}]] = 
    3 + q^(-16) + q^(-14) + q^(-12) + q^(-10) + 2/q^8 + 2/q^6 + 2/q^4 + 2/q^2 + 2*q^2 + 2*q^4 + 
     2*q^6 + 2*q^8 + q^10 + q^12 + q^14 + q^16;


fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0,0,0,0,0,0,1}]]=1/q^27+1/q^25+1/q^23+1/q^21+1/q^19+2/q^17+2/q^15+2/q^13+2/q^11+3/q^9+3/q^7+3/q^5+3/q^3+3/q+3 q+3 q^3+3 q^5+3 q^7+3 q^9+2 q^11+2 q^13+2 q^15+2 q^17+q^19+q^21+q^23+q^25+q^27;
fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0,0,0,0,0,1,0}]]=65+1/q^52+1/q^50+2/q^48+2/q^46+4/q^44+5/q^42+7/q^40+8/q^38+11/q^36+13/q^34+17/q^32+19/q^30+23/q^28+26/q^26+31/q^24+34/q^22+39/q^20+42/q^18+47/q^16+49/q^14+54/q^12+56/q^10+60/q^8+60/q^6+63/q^4+63/q^2+63 q^2+63 q^4+60 q^6+60 q^8+56 q^10+54 q^12+49 q^14+47 q^16+42 q^18+39 q^20+34 q^22+31 q^24+26 q^26+23 q^28+19 q^30+17 q^32+13 q^34+11 q^36+8 q^38+7 q^40+5 q^42+4 q^44+2 q^46+2 q^48+q^50+q^52;
fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0,0,0,0,1,0,0}]]=1/q^75+1/q^73+2/q^71+4/q^69+6/q^67+9/q^65+13/q^63+18/q^61+25/q^59+34/q^57+44/q^55+57/q^53+73/q^51+91/q^49+112/q^47+137/q^45+164/q^43+195/q^41+230/q^39+267/q^37+308/q^35+352/q^33+397/q^31+445/q^29+495/q^27+545/q^25+595/q^23+646/q^21+694/q^19+741/q^17+786/q^15+825/q^13+861/q^11+893/q^9+918/q^7+938/q^5+952/q^3+958/q+958 q+952 q^3+938 q^5+918 q^7+893 q^9+861 q^11+825 q^13+786 q^15+741 q^17+694 q^19+646 q^21+595 q^23+545 q^25+495 q^27+445 q^29+397 q^31+352 q^33+308 q^35+267 q^37+230 q^39+195 q^41+164 q^43+137 q^45+112 q^47+91 q^49+73 q^51+57 q^53+44 q^55+34 q^57+25 q^59+18 q^61+13 q^63+9 q^65+6 q^67+4 q^69+2 q^71+q^73+q^75


fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0,0,1,0,0,0,0}]]=319+1/q^66+1/q^64+2/q^62+3/q^60+5/q^58+7/q^56+10/q^54+13/q^52+18/q^50+23/q^48+30/q^46+37/q^44+47/q^42+56/q^40+68/q^38+80/q^36+95/q^34+109/q^32+126/q^30+141/q^28+160/q^26+177/q^24+196/q^22+212/q^20+231/q^18+246/q^16+263/q^14+276/q^12+290/q^10+299/q^8+309/q^6+313/q^4+319/q^2+319 q^2+313 q^4+309 q^6+299 q^8+290 q^10+276 q^12+263 q^14+246 q^16+231 q^18+212 q^20+196 q^22+177 q^24+160 q^26+141 q^28+126 q^30+109 q^32+95 q^34+80 q^36+68 q^38+56 q^40+47 q^42+37 q^44+30 q^46+23 q^48+18 q^50+13 q^52+10 q^54+7 q^56+5 q^58+3 q^60+2 q^62+q^64+q^66;
fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0,1,0,0,0,0,0}]]=1/q^49+1/q^47+1/q^45+2/q^43+3/q^41+4/q^39+5/q^37+7/q^35+8/q^33+10/q^31+12/q^29+14/q^27+17/q^25+19/q^23+21/q^21+24/q^19+27/q^17+29/q^15+31/q^13+33/q^11+35/q^9+37/q^7+38/q^5+38/q^3+39/q+39 q+38 q^3+38 q^5+37 q^7+35 q^9+33 q^11+31 q^13+29 q^15+27 q^17+24 q^19+21 q^21+19 q^23+17 q^25+14 q^27+12 q^29+10 q^31+8 q^33+7 q^35+5 q^37+4 q^39+3 q^41+2 q^43+q^45+q^47+q^49;
fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{1,0,0,0,0,0,0}]]=7+1/q^34+1/q^32+1/q^30+1/q^28+2/q^26+2/q^24+3/q^22+3/q^20+4/q^18+4/q^16+5/q^14+5/q^12+6/q^10+6/q^8+6/q^6+6/q^4+7/q^2+7 q^2+6 q^4+6 q^6+6 q^8+6 q^10+5 q^12+5 q^14+4 q^16+4 q^18+3 q^20+3 q^22+2 q^24+2 q^26+q^28+q^30+q^32+q^34;

fastQDimension[Subscript[E, 7]][Irrep[Subscript[E, 7]][{0, 0, 0, 0, 0, 0, 1}]] = 
    q^(-27) + q^(-25) + q^(-23) + q^(-21) + q^(-19) + 2/q^17 + 2/q^15 + 2/q^13 + 2/q^11 + 
     3/q^9 + 3/q^7 + 3/q^5 + 3/q^3 + 3/q + 3*q + 3*q^3 + 3*q^5 + 3*q^7 + 3*q^9 + 2*q^11 + 
     2*q^13 + 2*q^15 + 2*q^17 + q^19 + q^21 + q^23 + q^25 + q^27;


fastQDimension[Subscript[E, 8]][Irrep[Subscript[E, 8]][{0, 0, 0, 0, 0, 0, 0, 1}]] = 
    8 + q^(-58) + q^(-56) + q^(-54) + q^(-52) + q^(-50) + q^(-48) + 2/q^46 + 2/q^44 + 2/q^42 + 
     2/q^40 + 3/q^38 + 3/q^36 + 4/q^34 + 4/q^32 + 4/q^30 + 4/q^28 + 5/q^26 + 5/q^24 + 6/q^22 + 
     6/q^20 + 6/q^18 + 6/q^16 + 7/q^14 + 7/q^12 + 7/q^10 + 7/q^8 + 7/q^6 + 7/q^4 + 8/q^2 + 
     8*q^2 + 7*q^4 + 7*q^6 + 7*q^8 + 7*q^10 + 7*q^12 + 7*q^14 + 6*q^16 + 6*q^18 + 6*q^20 + 
     6*q^22 + 5*q^24 + 5*q^26 + 4*q^28 + 4*q^30 + 4*q^32 + 4*q^34 + 3*q^36 + 3*q^38 + 2*q^40 + 
     2*q^42 + 2*q^44 + 2*q^46 + q^48 + q^50 + q^52 + q^54 + q^56 + q^58;
 
fastQDimension[Subscript[E, 8]][Irrep[Subscript[E, 8]][{0, 1, 0, 0, 0, 0, 0, 0}]] = 
    3006 + q^(-136) + q^(-134) + q^(-132) + 2/q^130 + 3/q^128 + 4/q^126 + 6/q^124 + 8/q^122 + 
     10/q^120 + 13/q^118 + 17/q^116 + 21/q^114 + 27/q^112 + 33/q^110 + 40/q^108 + 49/q^106 + 
     60/q^104 + 71/q^102 + 85/q^100 + 100/q^98 + 117/q^96 + 137/q^94 + 160/q^92 + 184/q^90 + 
     212/q^88 + 241/q^86 + 274/q^84 + 311/q^82 + 352/q^80 + 394/q^78 + 441/q^76 + 490/q^74 + 
     544/q^72 + 602/q^70 + 664/q^68 + 727/q^66 + 796/q^64 + 866/q^62 + 941/q^60 + 1020/q^58 + 
     1102/q^56 + 1183/q^54 + 1270/q^52 + 1357/q^50 + 1448/q^48 + 1540/q^46 + 1633/q^44 + 
     1723/q^42 + 1818/q^40 + 1910/q^38 + 2003/q^36 + 2095/q^34 + 2185/q^32 + 2268/q^30 + 
     2354/q^28 + 2435/q^26 + 2514/q^24 + 2587/q^22 + 2656/q^20 + 2716/q^18 + 2776/q^16 + 
     2828/q^14 + 2875/q^12 + 2914/q^10 + 2947/q^8 + 2969/q^6 + 2990/q^4 + 3001/q^2 + 3001*q^2 + 
     2990*q^4 + 2969*q^6 + 2947*q^8 + 2914*q^10 + 2875*q^12 + 2828*q^14 + 2776*q^16 + 
     2716*q^18 + 2656*q^20 + 2587*q^22 + 2514*q^24 + 2435*q^26 + 2354*q^28 + 2268*q^30 + 
     2185*q^32 + 2095*q^34 + 2003*q^36 + 1910*q^38 + 1818*q^40 + 1723*q^42 + 1633*q^44 + 
     1540*q^46 + 1448*q^48 + 1357*q^50 + 1270*q^52 + 1183*q^54 + 1102*q^56 + 1020*q^58 + 
     941*q^60 + 866*q^62 + 796*q^64 + 727*q^66 + 664*q^68 + 602*q^70 + 544*q^72 + 490*q^74 + 
     441*q^76 + 394*q^78 + 352*q^80 + 311*q^82 + 274*q^84 + 241*q^86 + 212*q^88 + 184*q^90 + 
     160*q^92 + 137*q^94 + 117*q^96 + 100*q^98 + 85*q^100 + 71*q^102 + 60*q^104 + 49*q^106 + 
     40*q^108 + 33*q^110 + 27*q^112 + 21*q^114 + 17*q^116 + 13*q^118 + 10*q^120 + 8*q^122 + 
     6*q^124 + 4*q^126 + 3*q^128 + 2*q^130 + q^132 + q^134 + q^136;
 
fastQDimension[Subscript[E, 8]][Irrep[Subscript[E, 8]][{1, 0, 0, 0, 0, 0, 0, 0}]] = 
    97 + q^(-92) + q^(-90) + q^(-88) + q^(-86) + 2/q^84 + 2/q^82 + 3/q^80 + 4/q^78 + 5/q^76 + 
     5/q^74 + 7/q^72 + 8/q^70 + 10/q^68 + 11/q^66 + 13/q^64 + 14/q^62 + 17/q^60 + 19/q^58 + 
     22/q^56 + 24/q^54 + 27/q^52 + 29/q^50 + 33/q^48 + 36/q^46 + 40/q^44 + 42/q^42 + 46/q^40 + 
     49/q^38 + 54/q^36 + 57/q^34 + 61/q^32 + 63/q^30 + 67/q^28 + 70/q^26 + 75/q^24 + 77/q^22 + 
     81/q^20 + 82/q^18 + 85/q^16 + 87/q^14 + 91/q^12 + 91/q^10 + 93/q^8 + 93/q^6 + 95/q^4 + 
     95/q^2 + 95*q^2 + 95*q^4 + 93*q^6 + 93*q^8 + 91*q^10 + 91*q^12 + 87*q^14 + 85*q^16 + 
     82*q^18 + 81*q^20 + 77*q^22 + 75*q^24 + 70*q^26 + 67*q^28 + 63*q^30 + 61*q^32 + 57*q^34 + 
     54*q^36 + 49*q^38 + 46*q^40 + 42*q^42 + 40*q^44 + 36*q^46 + 33*q^48 + 29*q^50 + 27*q^52 + 
     24*q^54 + 22*q^56 + 19*q^58 + 17*q^60 + 14*q^62 + 13*q^64 + 11*q^66 + 10*q^68 + 8*q^70 + 
     7*q^72 + 5*q^74 + 5*q^76 + 4*q^78 + 3*q^80 + 2*q^82 + 2*q^84 + q^86 + q^88 + q^90 + q^92;

fastQDimension[Subscript[E, 8]][Irrep[Subscript[E, 8]][{0, 0, 0, 0, 0, 0, 1, 0}]] =676+q^(-114)+q^(-112)+2/q^110+2/q^108+3/q^106+4/q^104+6/q^102+7/q^100+9/q^98+11/q^96+14/q^94+17/q^92+22/q^90+25/q^88+30/q^86+35/q^84+42/q^82+49/q^80+58/q^78+65/q^76+75/q^74+85/q^72+98/q^70+109/q^68+124/q^66+136/q^64+152/q^62+168/q^60+187/q^58+204/q^56+224/q^54+241/q^52+263/q^50+283/q^48+307/q^46+327/q^44+351/q^42+371/q^40+396/q^38+418/q^36+443/q^34+463/q^32+486/q^30+504/q^28+528/q^26+547/q^24+568/q^22+583/q^20+601/q^18+613/q^16+630/q^14+641/q^12+653/q^10+658/q^8+667/q^6+669/q^4+676/q^2+676*q^2+669*q^4+667*q^6+658*q^8+653*q^10+641*q^12+630*q^14+613*q^16+601*q^18+583*q^20+568*q^22+547*q^24+528*q^26+504*q^28+486*q^30+463*q^32+443*q^34+418*q^36+396*q^38+371*q^40+351*q^42+327*q^44+307*q^46+283*q^48+263*q^50+241*q^52+224*q^54+204*q^56+187*q^58+168*q^60+152*q^62+136*q^64+124*q^66+109*q^68+98*q^70+85*q^72+75*q^74+65*q^76+58*q^78+49*q^80+42*q^82+35*q^84+30*q^86+25*q^88+22*q^90+17*q^92+14*q^94+11*q^96+9*q^98+7*q^100+6*q^102+4*q^104+3*q^106+2*q^108+2*q^110+q^112+q^114


End[];


EndPackage[];
