(* ::Package:: *)

(************************************************************************)
(* This file was generated automatically by the Mathematica front end.  *)
(* It contains Initialization cells from a Notebook file, which         *)
(* typically will have the same name as this file except ending in      *)
(* ".nb" instead of ".m".                                               *)
(*                                                                      *)
(* This file is intended to be loaded into the Mathematica kernel using *)
(* the package loading commands Get or Needs.  Doing so is equivalent   *)
(* to using the Evaluate Initialization Cells menu command in the front *)
(* end.                                                                 *)
(*                                                                      *)
(* DO NOT EDIT THIS FILE.  This entire file is regenerated              *)
(* automatically each time the parent Notebook file is saved in the     *)
(* Mathematica front end.  Any changes you make to this file will be    *)
(* overwritten.                                                         *)
(************************************************************************)



(* ::Code:: *)
Int[u_*(c_+d_.*x_)^n_.*(a_+b_.*x_^2)^p_.,x_Symbol] :=
  Int[u*(c+d*x)^(n+p)*(a/c+b/d*x)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b*c^2+a*d^2,0] && (IntegerQ[p] || GtQ[a,0] && GtQ[c,0] && Not[IntegerQ[n]])


(* ::Code:: *)
(* Int[u_*(d_+e_.*x_)^q_.*(a_+b_.*x_+c_.*x_^2)^p_,x_Symbol] :=
  Int[u*(a+b*x+c*x^2)^(p+q)/(a/d+c*x/e)^q,x] /;
FreeQ[{a,b,c,d,e,p},x] && EqQ[c*d^2-b*d*e+a*e^2,0] && IntegerQ[q] && FractionQ[p] && LtQ[0,(p+q)^2,p^2] *)


(* ::Code:: *)
(* Int[u_*(d_+e_.*x_)^q_.*(a_+c_.*x_^2)^p_,x_Symbol] :=
(*Int[u*(a+c*x^2)^(p+q)/(a/d+c*x/e)^q,x] /; *)
  d^(2*q)/a^q \[Star] Int[u*(a+c*x^2)^(p+q)/(d-e*x)^q,x] /;
FreeQ[{a,c,d,e,p},x] && EqQ[c*d^2+a*e^2,0] && IntegerQ[q] && FractionQ[p] && LtQ[0,(p+q)^2,p^2] *)


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*x_^n_)^p_.*Fx_,x_Symbol] :=
  Int[x^(m+n*p)*(b+a*x^(-n))^p*Fx,x] /;
FreeQ[{a,b,m,n},x] && IntegerQ[p] && NegQ[n]


(* ::Code:: *)
Int[(c_.*x_)^m_.*u_,x_Symbol] :=
  Int[ExpandIntegrand[(c*x)^m*u,x],x] /;
FreeQ[{c,m},x] && SumQ[u] && Not[LinearQ[u,x]] && Not[MatchQ[u,a_+b_.*v_ /; FreeQ[{a,b},x] && InverseFunctionQ[v]]]


(* ::Code:: *)
Int[u_.*(a_+b_.*v_)^m_.*(c_+d_.*v_)^n_.,x_Symbol] :=
  (b/d)^m \[Star] Int[u*(c+d*v)^(m+n),x] /;
FreeQ[{a,b,c,d,n},x] && EqQ[b*c-a*d,0] && IntegerQ[m] && (Not[IntegerQ[n]] || SimplerQ[c+d*x,a+b*x])


(* ::Code:: *)
Int[u_.*(a_+b_.*v_)^m_*(c_+d_.*v_)^n_,x_Symbol] :=
  (b/d)^m \[Star] Int[u*(c+d*v)^(m+n),x] /;
FreeQ[{a,b,c,d,m,n},x] && EqQ[b*c-a*d,0] && GtQ[b/d,0] && Not[IntegerQ[m] || IntegerQ[n]]


(* ::Code:: *)
Int[u_.*(a_+b_.*v_)^m_*(c_+d_.*v_)^n_,x_Symbol] :=
  (a+b*v)^m/(c+d*v)^m \[Star] Int[u*(c+d*v)^(m+n),x] /;
FreeQ[{a,b,c,d,m,n},x] && EqQ[b*c-a*d,0] && Not[IntegerQ[m] || IntegerQ[n] || GtQ[b/d,0]]


(* ::Code:: *)
(* Int[u_.*(a_.*v_)^m_*(b_.*v_+c_.*v_^2),x_Symbol] :=
  1/a \[Star] Int[u*(a*v)^(m+1)*(b+c*v),x] /;
FreeQ[{a,b,c},x] && LeQ[m,-1] *)


(* ::Code:: *)
Int[u_.*(a_+b_.*v_)^m_*(A_.+B_.*v_+C_.*v_^2),x_Symbol] :=
  1/b^2 \[Star] Int[u*(a+b*v)^(m+1)*Simp[b*B-a*C+b*C*v,x],x] /;
FreeQ[{a,b,A,B,C},x] && EqQ[A*b^2-a*b*B+a^2*C,0] && LeQ[m,-1]


(* ::Code:: *)
Int[u_.*(a_+b_.*x_^n_.)^m_.*(c_+d_.*x_^q_.)^p_.,x_Symbol] :=
  (d/a)^p \[Star] Int[u*(a+b*x^n)^(m+p)/x^(n*p),x] /;
FreeQ[{a,b,c,d,m,n},x] && EqQ[q,-n] && IntegerQ[p] && EqQ[a*c-b*d,0] && Not[IntegerQ[m] && NegQ[n]]


(* ::Code:: *)
Int[u_.*(a_+b_.*x_^n_.)^m_.*(c_+d_.*x_^j_)^p_.,x_Symbol] :=
  (-b^2/d)^m \[Star] Int[u*(a-b*x^n)^(-m),x] /;
FreeQ[{a,b,c,d,m,n,p},x] && EqQ[j,2*n] && EqQ[p,-m] && EqQ[b^2*c+a^2*d,0] && GtQ[a,0] && LtQ[d,0] && GtQ[b^2,0]


(* ::Code:: *)
(* Int[u_*(a_+b_.*x_+c_.*x_^2)^p_.,x_Symbol] :=
  Int[u*Cancel[(b/2+c*x)^(2*p)/c^p],x] /;
FreeQ[{a,b,c},x] && EqQ[b^2-4*a*c,0] && IntegerQ[p] *)


(* ::Code:: *)
(* Int[u_*(a_+b_.*x_^n_+c_.*x_^n2_.)^p_.,x_Symbol] :=
  1/c^p \[Star] Int[u*(b/2+c*x^n)^(2*p),x] /;
FreeQ[{a,b,c,n},x] && EqQ[n2,2*n] && EqQ[b^2-4*a*c,0] && IntegerQ[p] *)


(* ::Code:: *)
Int[Pp_*Qq_^m_.,x_Symbol] :=
  With[{p=Expon[Pp,x],q=Expon[Qq,x]},
  Coeff[Pp,x,p]*x^(p-q+1)*Qq^(m+1)/((p+m*q+1)*Coeff[Qq,x,q]) /;
 NeQ[p+m*q+1,0] && EqQ[(p+m*q+1)*Coeff[Qq,x,q]*Pp,Coeff[Pp,x,p]*x^(p-q)*((p-q+1)*Qq+(m+1)*x*D[Qq,x])]] /;
FreeQ[m,x] && PolyQ[Pp,x] && PolyQ[Qq,x] && NeQ[m,-1]


(* ::Code:: *)
Int[x_^m_.*(a1_+b1_.*x_^n_.)^p_*(a2_+b2_.*x_^n_.)^p_,x_Symbol] :=
  (a1+b1*x^n)^(p+1)*(a2+b2*x^n)^(p+1)/(2*b1*b2*n*(p+1)) /;
FreeQ[{a1,b1,a2,b2,m,n,p},x] && EqQ[a2*b1+a1*b2,0] && EqQ[m-2*n+1,0] && NeQ[p,-1]


(* ::Code:: *)
Int[Pp_*Qq_^m_.*Rr_^n_.,x_Symbol] :=
  With[{p=Expon[Pp,x],q=Expon[Qq,x],r=Expon[Rr,x]},
  Coeff[Pp,x,p]*x^(p-q-r+1)*Qq^(m+1)*Rr^(n+1)/((p+m*q+n*r+1)*Coeff[Qq,x,q]*Coeff[Rr,x,r]) /;
 NeQ[p+m*q+n*r+1,0] && 
 EqQ[(p+m*q+n*r+1)*Coeff[Qq,x,q]*Coeff[Rr,x,r]*Pp,Coeff[Pp,x,p]*x^(p-q-r)*((p-q-r+1)*Qq*Rr+(m+1)*x*Rr*D[Qq,x]+(n+1)*x*Qq*D[Rr,x])]] /;
FreeQ[{m,n},x] && PolyQ[Pp,x] && PolyQ[Qq,x] && PolyQ[Rr,x] && NeQ[m,-1] && NeQ[n,-1]


(* ::Code:: *)
Int[Fx_.*Px_^p_.,x_Symbol] :=
  With[{k=Expon[Px,x,Min]},
  Int[Fx*x^(k*p)*PolynomialQuotient[Px,x^k,x]^p,x] /;
 IGtQ[k,0]] /;
PolyQ[Px,x] && IntegerQ[p] && Not[MonomialQ[Px,x]] && (ILtQ[p,0] || Not[PolyQ[Fx,x]])


(* ::Code:: *)
Int[(a_.*x_^r_.+b_.*x_^s_.)^p_.*Fx_.,x_Symbol] :=
  Int[x^(p*r)*(a+b*x^(s-r))^p*Fx,x] /;
FreeQ[{a,b,r,s},x] && IntegerQ[p] && PosQ[s-r] && Not[EqQ[p,1] && EqQ[Fx,1]]


(* ::Code:: *)
Int[(a_.*x_^r_.+b_.*x_^s_.+c_.*x_^t_.)^p_.*Fx_.,x_Symbol] :=
  Int[x^(p*r)*(a+b*x^(s-r)+c*x^(t-r))^p*Fx,x] /;
FreeQ[{a,b,c,r,s,t},x] && IntegerQ[p] && PosQ[s-r] && PosQ[t-r] && Not[EqQ[p,1] && EqQ[Fx,1]]


(* ::Code:: *)
Int[(a_.*x_^r_.+b_.*x_^s_.+c_.*x_^t_.+d_.*x_^q_.)^p_.*Fx_.,x_Symbol] :=
  Int[x^(p*r)*(a+b*x^(s-r)+c*x^(t-r)+d*x^(q-r))^p*Fx,x] /;
FreeQ[{a,b,c,d,r,s,t,q},x] && IntegerQ[p] && PosQ[s-r] && PosQ[t-r] && PosQ[q-r] && Not[EqQ[p,1] && EqQ[Fx,1]]


(* ::Code:: *)
Int[v_^m_.*(b_*v_)^n_*Fx_.,x_Symbol] :=
  1/b^m \[Star] Int[(b*v)^(m+n)*Fx,x] /;
FreeQ[{b,n},x] && IntegerQ[m]


(* ::Code:: *)
Int[(a_.*v_)^m_*(b_.*v_)^n_*Fx_.,x_Symbol] :=
  a^(m+1/2)*b^(n-1/2)*Sqrt[b*v]/Sqrt[a*v] \[Star] Int[v^(m+n)*Fx,x] /;
FreeQ[{a,b,m},x] && Not[IntegerQ[m]] && IGtQ[n+1/2,0] && IntegerQ[m+n]


(* ::Code:: *)
(* Int[u_.*(a_.*v_)^m_*(b_.*v_)^n_,x_Symbol] :=
  b^(n-1/2)*Sqrt[b*v]/(a^(n-1/2)*Sqrt[a*v]) \[Star] Int[u*(a*v)^(m+n),x] /;
FreeQ[{a,b,m},x] && Not[IntegerQ[m]] && IGtQ[n+1/2,0] && Not[IntegerQ[m+n]] *)


(* ::Code:: *)
Int[(a_.*v_)^m_*(b_.*v_)^n_*Fx_.,x_Symbol] :=
  a^(m-1/2)*b^(n+1/2)*Sqrt[a*v]/Sqrt[b*v] \[Star] Int[v^(m+n)*Fx,x] /;
FreeQ[{a,b,m},x] && Not[IntegerQ[m]] && ILtQ[n-1/2,0] && IntegerQ[m+n]


(* ::Code:: *)
(* Int[u_.*(a_.*v_)^m_*(b_.*v_)^n_,x_Symbol] :=
  b^(n+1/2)*Sqrt[a*v]/(a^(n+1/2)*Sqrt[b*v]) \[Star] Int[u*(a*v)^(m+n),x] /;
FreeQ[{a,b,m},x] && Not[IntegerQ[m]] && ILtQ[n-1/2,0] && Not[IntegerQ[m+n]] *)


(* ::Code:: *)
Int[(a_.*v_)^m_*(b_.*v_)^n_*Fx_.,x_Symbol] :=
  a^(m+n)*(b*v)^n/(a*v)^n \[Star] Int[v^(m+n)*Fx,x] /;
FreeQ[{a,b,m,n},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && IntegerQ[m+n]


(* ::Code:: *)
Int[(a_.*v_)^m_*(b_.*v_)^n_*Fx_.,x_Symbol] :=
  b^IntPart[n]*(b*v)^FracPart[n]/(a^IntPart[n]*(a*v)^FracPart[n]) \[Star] Int[(a*v)^(m+n)*Fx,x] /;
FreeQ[{a,b,m,n},x] && Not[IntegerQ[m]] && Not[IntegerQ[n]] && Not[IntegerQ[m+n]]


(* ::Code:: *)
Int[x_^m_*Fx_,x_Symbol] :=
  With[{k=Denominator[m]},
  k \[Star] Subst[Int[x^(k*(m+1)-1)*SubstPower[Fx,x,k],x],x,x^(1/k)]] /;
FractionQ[m] && AlgebraicFunctionQ[Fx,x]


(* ::Code:: *)
Int[u_.*(a1_+b1_.*x_^non2_.)^p_.*(a2_+b2_.*x_^non2_.)^p_.*(c_+d_.*x_^n_.)^q_.,x_Symbol] :=
  Int[u*(a1*a2+b1*b2*x^n)^p*(c+d*x^n)^q,x] /;
FreeQ[{a1,b1,a2,b2,c,d,n,p,q},x] && EqQ[non2,n/2] && EqQ[a2*b1+a1*b2,0] && (IntegerQ[p] || GtQ[a1,0] && GtQ[a2,0])


(* ::Code:: *)
Int[u_.*(a1_+b1_.*x_^non2_.)^p_.*(a2_+b2_.*x_^non2_.)^p_.*(c_+d_.*x_^n_.+e_.*x_^n2_.)^q_.,x_Symbol] :=
  Int[u*(a1*a2+b1*b2*x^n)^p*(c+d*x^n+e*x^(2*n))^q,x] /;
FreeQ[{a1,b1,a2,b2,c,d,e,n,p,q},x] && EqQ[non2,n/2] && EqQ[n2,2*n] && EqQ[a2*b1+a1*b2,0] && (IntegerQ[p] || GtQ[a1,0] && GtQ[a2,0])


(* ::Code:: *)
Int[u_.*(a1_+b1_.*x_^non2_.)^p_*(a2_+b2_.*x_^non2_.)^p_*(c_+d_.*x_^n_.)^q_.,x_Symbol] :=
  (a1+b1*x^(n/2))^FracPart[p]*(a2+b2*x^(n/2))^FracPart[p]/(a1*a2+b1*b2*x^n)^FracPart[p] \[Star] 
    Int[u*(a1*a2+b1*b2*x^n)^p*(c+d*x^n)^q,x] /;
FreeQ[{a1,b1,a2,b2,c,d,n,p,q},x] && EqQ[non2,n/2] && EqQ[a2*b1+a1*b2,0] && Not[EqQ[n,2] && IGtQ[q,0]]


(* ::Code:: *)
Int[u_.*(a1_+b1_.*x_^non2_.)^p_.*(a2_+b2_.*x_^non2_.)^p_.*(c_+d_.*x_^n_.+e_.*x_^n2_.)^q_.,x_Symbol] :=
  (a1+b1*x^(n/2))^FracPart[p]*(a2+b2*x^(n/2))^FracPart[p]/(a1*a2+b1*b2*x^n)^FracPart[p] \[Star] 
    Int[u*(a1*a2+b1*b2*x^n)^p*(c+d*x^n+e*x^(2*n))^q,x] /;
FreeQ[{a1,b1,a2,b2,c,d,e,n,p,q},x] && EqQ[non2,n/2] && EqQ[n2,2*n] && EqQ[a2*b1+a1*b2,0]


(* ::Code:: *)
Int[(a_+b_.*x_^n_)^p_.*(c_+d_.*x_^n_)^q_.*(e1_+f1_.*x_^n2_.)^r_.*(e2_+f2_.*x_^n2_.)^r_.,x_Symbol] :=
  Int[(a+b*x^n)^p*(c+d*x^n)^q*(e1*e2+f1*f2*x^n)^r,x] /;
FreeQ[{a,b,c,d,e1,f1,e2,f2,n,p,q,r},x] && EqQ[n2,n/2] && EqQ[e2*f1+e1*f2,0] && (IntegerQ[r] || GtQ[e1,0] && GtQ[e2,0])


(* ::Code:: *)
Int[(a_+b_.*x_^n_)^p_.*(c_+d_.*x_^n_)^q_.*(e1_+f1_.*x_^n2_.)^r_.*(e2_+f2_.*x_^n2_.)^r_.,x_Symbol] :=
  (e1+f1*x^(n/2))^FracPart[r]*(e2+f2*x^(n/2))^FracPart[r]/(e1*e2+f1*f2*x^n)^FracPart[r] \[Star] 
    Int[(a+b*x^n)^p*(c+d*x^n)^q*(e1*e2+f1*f2*x^n)^r,x] /;
FreeQ[{a,b,c,d,e1,f1,e2,f2,n,p,q,r},x] && EqQ[n2,n/2] && EqQ[e2*f1+e1*f2,0]


(* ::Code:: *)
Int[u_.*(c_.*(d_*(a_.+b_.* x_))^q_)^p_,x_Symbol] :=
  (c*(d*(a+b*x))^q)^p/(a+b*x)^(p*q) \[Star] Int[u*(a+b*x)^(p*q),x] /;
FreeQ[{a,b,c,d,q,p},x] && Not[IntegerQ[q]] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[u_.*(c_.*(d_.*(a_.+b_.* x_)^n_)^q_)^p_,x_Symbol] :=
  (c*(d*(a+b*x)^n)^q)^p/(a+b*x)^(n*p*q) \[Star] Int[u*(a+b*x)^(n*p*q),x] /;
FreeQ[{a,b,c,d,n,q,p},x] && Not[IntegerQ[q]] && Not[IntegerQ[p]]


(* ::Code:: *)
Int[u_.*(c_.*(a_.+b_.*x_^n_.)^q_)^p_,x_Symbol] :=
  Simp[(c*(a+b*x^n)^q)^p/(a+b*x^n)^(p*q)] \[Star] Int[u*(a+b*x^n)^(p*q),x] /;
FreeQ[{a,b,c,n,p,q},x] && GeQ[a,0]


(* ::Code:: *)
Int[u_.*(c_.*(a_+b_.*x_^n_.)^q_)^p_,x_Symbol] :=
  Simp[(c*(a+b*x^n)^q)^p/(1+b*x^n/a)^(p*q)] \[Star] Int[u*(1+b*x^n/a)^(p*q),x] /;
FreeQ[{a,b,c,n,p,q},x] && Not[GeQ[a,0]]


(* ::Code:: *)
Int[u_.*(e_.*(a_.+b_.*x_^n_.)^q_.*(c_+d_.*x_^n_.)^q_.)^p_,x_Symbol] :=
  Int[u*(e*(d/b)^q*(a+b*x^n)^(2*q))^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && IntegerQ[q] && EqQ[b*c-a*d,0]


(* ::Code:: *)
Int[u_.*(e_.*(a_.+b_.*x_^n_.)^q_*(c_+d_.*x_^n_.)^q_)^p_,x_Symbol] :=
  Int[u*(e*(-a^2*d/b+b*d*x^(2*n))^q)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && IntegerQ[q] && EqQ[b*c+a*d,0]


(* ::Code:: *)
(* Int[u_.*((a_.+b_.*x_^n_.)*(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Int[u*(a+b*x^n)^p*(c+d*x^n)^p,x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[b+d,0] && GtQ[a,0] && GtQ[c,0] *)


(* ::Code:: *)
Int[u_.*(e_.*(a_.+b_.*x_^n_.)*(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Int[u*(a*c*e+(b*c+a*d)*e*x^n+b*d*e*x^(2*n))^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x]


(* ::Code:: *)
Int[u_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  (b*e/d)^p \[Star] Int[u,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c-a*d,0]


(* ::Code:: *)
Int[u_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Int[u*(a*e+b*e*x^n)^p/(c+d*x^n)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && GtQ[b*d*e,0] && GtQ[c-a*d/b,0]


(* ::Code:: *)
(* Int[u_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Int[u*(a*e+b*e*x^n)^p/(c+d*x^n)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c+a*d,0] && GtQ[b*e/d,0] && GtQ[c,0] *)


(* ::Code:: *)
(* Int[u_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Int[u*(-a*e-b*e*x^n)^p/(-c-d*x^n)^p,x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[b*c+a*d,0] && GtQ[b*e/d,0] && LtQ[c,0] *)


(* ::Code:: *)
Int[(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  With[{q=Denominator[p]},
  q*e*(b*c-a*d)/n \[Star] Subst[
    Int[x^(q*(p+1)-1)*(-a*e+c*x^q)^(1/n-1)/(b*e-d*x^q)^(1/n+1),x],x,(e*(a+b*x^n)/(c+d*x^n))^(1/q)]] /;
FreeQ[{a,b,c,d,e},x] && FractionQ[p] && IntegerQ[1/n]


(* ::Code:: *)
Int[x_^m_.*(e_.*(a_.+b_.*x_)/(c_+d_.*x_))^p_,x_Symbol] :=
  With[{q=Denominator[p]},
  q*e*(b*c-a*d) \[Star] Subst[Int[x^(q*(p+1)-1)*(-a*e+c*x^q)^m/(b*e-d*x^q)^(m+2),x],x,(e*(a+b*x)/(c+d*x))^(1/q)]] /;
FreeQ[{a,b,c,d,e,m},x] && FractionQ[p] && IntegerQ[m]


(* ::Code:: *)
Int[x_^m_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  1/n \[Star] Subst[Int[x^(Simplify[(m+1)/n]-1)*(e*(a+b*x)/(c+d*x))^p,x],x,x^n] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && IntegerQ[Simplify[(m+1)/n]]


(* ::Code:: *)
Int[(f_*x_)^m_*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  Simp[(c*x)^m/x^m] \[Star] Int[x^m*(e*(a+b*x^n)/(c+d*x^n))^p,x] /;
FreeQ[{a,b,c,d,e,f,m,n,p},x] && IntegerQ[Simplify[(m+1)/n]]


(* ::Code:: *)
Int[u_^r_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  With[{q=Denominator[p]},
  q*e*(b*c-a*d)/n \[Star] Subst[Int[SimplifyIntegrand[x^(q*(p+1)-1)*(-a*e+c*x^q)^(1/n-1)/(b*e-d*x^q)^(1/n+1)*
    ReplaceAll[u,x->(-a*e+c*x^q)^(1/n)/(b*e-d*x^q)^(1/n)]^r,x],x],x,(e*(a+b*x^n)/(c+d*x^n))^(1/q)]] /;
FreeQ[{a,b,c,d,e},x] && PolynomialQ[u,x] && FractionQ[p] && IntegerQ[1/n] && IntegerQ[r]


(* ::Code:: *)
Int[x_^m_.*u_^r_.*(e_.*(a_.+b_.*x_^n_.)/(c_+d_.*x_^n_.))^p_,x_Symbol] :=
  With[{q=Denominator[p]},
  q*e*(b*c-a*d)/n \[Star] Subst[Int[SimplifyIntegrand[x^(q*(p+1)-1)*(-a*e+c*x^q)^((m+1)/n-1)/(b*e-d*x^q)^((m+1)/n+1)*
    ReplaceAll[u,x->(-a*e+c*x^q)^(1/n)/(b*e-d*x^q)^(1/n)]^r,x],x],x,(e*(a+b*x^n)/(c+d*x^n))^(1/q)]] /;
FreeQ[{a,b,c,d,e},x] && PolynomialQ[u,x] && FractionQ[p] && IntegerQ[1/n] && IntegersQ[m,r]


(* ::Code:: *)
Int[u_.*(a_+b_./(c_+d_.*x_^n_))^p_,x_Symbol] :=
  Int[u*((b+a*c+a*d*x^n)/(c+d*x^n))^p,x] /;
FreeQ[{a,b,c,d,n,p},x]


(* ::Code:: *)
Int[Fx_.*(e_.*(a_.+b_.*x_^n_.)^p_.*(c_+d_.*x_^n_.)^q_.)^m_,x_Symbol] :=
  Simp[(e*(a+b*x^n)^p*(c+d*x^n)^q)^m/((a+b*x^n)^(m*p)*(c+d*x^n)^(m*q))] \[Star] 
    Int[Fx*(a+b*x^n)^(m*p)*(c+d*x^n)^(m*q),x] /;
FreeQ[{a,b,c,d,e,m,n,p,q},x]


(* ::Code:: *)
Int[Fx_.*(g_.*(a_.+b_.*x_^n_.)^p_.*(c_+d_.*x_^n_.)^q_.*(e_+f_.*x_^n_.)^r_.)^m_,x_Symbol] :=
  Simp[(g*(a+b*x^n)^p*(c+d*x^n)^q*(e+f*x^n)^r)^m/((a+b*x^n)^(m*p)*(c+d*x^n)^(m*q)*(e+f*x^n)^(m*r))] \[Star] 
    Int[Fx*(a+b*x^n)^(m*p)*(c+d*x^n)^(m*q)*(e+f*x^n)^(m*r),x] /;
FreeQ[{a,b,c,d,e,f,g,m,n,p,q,r},x]


(* ::Code:: *)
Int[(a_.+b_.*(c_./x_)^n_)^p_,x_Symbol] :=
  -c \[Star] Subst[Int[(a+b*x^n)^p/x^2,x],x,c/x] /;
FreeQ[{a,b,c,n,p},x]


(* ::Code:: *)
Int[x_^m_.*(a_.+b_.*(c_./x_)^n_)^p_,x_Symbol] :=
  -c^(m+1) \[Star] Subst[Int[(a+b*x^n)^p/x^(m+2),x],x,c/x] /;
FreeQ[{a,b,c,n,p},x] && IntegerQ[m]


(* ::Code:: *)
Int[(d_.*x_)^m_*(a_.+b_.*(c_./x_)^n_)^p_,x_Symbol] :=
  -c*(d*x)^m*(c/x)^m \[Star] Subst[Int[(a+b*x^n)^p/x^(m+2),x],x,c/x] /;
FreeQ[{a,b,c,d,m,n,p},x] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[(a_.+b_.*(d_./x_)^n_+c_.*(d_./x_)^n2_.)^p_,x_Symbol] :=
  -d \[Star] Subst[Int[(a+b*x^n+c*x^(2*n))^p/x^2,x],x,d/x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n2,2*n]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*(d_./x_)^n_+c_.*(d_./x_)^n2_.)^p_,x_Symbol] :=
  -d^(m+1) \[Star] Subst[Int[(a+b*x^n+c*x^(2*n))^p/x^(m+2),x],x,d/x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n2,2*n] && IntegerQ[m]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*(d_./x_)^n_+c_.*(d_./x_)^n2_.)^p_,x_Symbol] :=
  -d*(e*x)^m*(d/x)^m \[Star] Subst[Int[(a+b*x^n+c*x^(2*n))^p/x^(m+2),x],x,d/x] /;
FreeQ[{a,b,c,d,e,m,n,p},x] && EqQ[n2,2*n] && Not[IntegerQ[m]]


(* ::Code:: *)
Int[(a_.+b_.*(d_./x_)^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  -d \[Star] Subst[Int[(a+b*x^n+c/d^(2*n)*x^(2*n))^p/x^2,x],x,d/x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n2,-2*n] && IntegerQ[2*n]


(* ::Code:: *)
Int[x_^m_.*(a_+b_.*(d_./x_)^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  -d^(m+1) \[Star] Subst[Int[(a+b*x^n+c/d^(2*n)*x^(2*n))^p/x^(m+2),x],x,d/x] /;
FreeQ[{a,b,c,d,n,p},x] && EqQ[n2,-2*n] && IntegerQ[2*n] && IntegerQ[m]


(* ::Code:: *)
Int[(e_.*x_)^m_*(a_+b_.*(d_./x_)^n_+c_.*x_^n2_.)^p_,x_Symbol] :=
  -d*(e*x)^m*(d/x)^m \[Star] Subst[Int[(a+b*x^n+c/d^(2*n)*x^(2*n))^p/x^(m+2),x],x,d/x] /;
FreeQ[{a,b,c,d,e,n,p},x] && EqQ[n2,-2*n] && Not[IntegerQ[m]] && IntegerQ[2*n]


(* ::Code:: *)
Int[u_.*(e_.*(a_+b_.*x_^n_.)^r_.)^p_*(f_.*(c_+d_.*x_^n_.)^s_)^q_,x_Symbol] :=
  (e*(a+b*x^n)^r)^p*(f*(c+d*x^n)^s)^q/((a+b*x^n)^(p*r)*(c+d*x^n)^(q*s)) \[Star] 
    Int[u*(a+b*x^n)^(p*r)*(c+d*x^n)^(q*s),x] /;
FreeQ[{a,b,c,d,e,f,n,p,q,r,s},x]


(* ::Code:: *)
Int[u_.*Px_,x_Symbol] :=
  With[{a=Rt[Coeff[Px,x^2,0],Expon[Px,x^2]],b=Rt[Coeff[Px,x^2,Expon[Px,x^2]],Expon[Px,x^2]]},
  Int[u*(a+b*x^2)^Expon[Px,x^2],x] /;
 EqQ[Px,(a+b*x^2)^Expon[Px,x^2]]] /;
PolyQ[Px,x^2] && GtQ[Expon[Px,x^2],1] && NeQ[Coeff[Px,x^2,0],0] && Not[MatchQ[Px,a_.*v_^Expon[Px,x^2] /; FreeQ[a,x] && BinomialQ[v,x,2]]] 


(* ::Code:: *)
Int[u_.*Px_^p_,x_Symbol] :=
  With[{a=Rt[Coeff[Px,x^2,0],Expon[Px,x^2]],b=Rt[Coeff[Px,x^2,Expon[Px,x^2]],Expon[Px,x^2]]},
  Int[u*(a+b*x^2)^(Expon[Px,x^2]*p),x] /;
 EqQ[Px,(a+b*x^2)^Expon[Px,x^2]]] /;
IntegerQ[p] && PolyQ[Px,x^2] && GtQ[Expon[Px,x^2],1] && NeQ[Coeff[Px,x^2,0],0]


(* ::Code:: *)
Int[u_.*Px_^p_,x_Symbol] :=
  With[{a=Rt[Coeff[Px,x^2,0],Expon[Px,x^2]],b=Rt[Coeff[Px,x^2,Expon[Px,x^2]],Expon[Px,x^2]]},
  ((a+b*x^2)^Expon[Px,x^2])^p/(a+b*x^2)^(Expon[Px,x^2]*p) \[Star] Int[u*(a+b*x^2)^(Expon[Px,x^2]*p),x] /;
 EqQ[Px,(a+b*x^2)^Expon[Px,x^2]]] /;
Not[IntegerQ[p]] && PolyQ[Px,x^2] && GtQ[Expon[Px,x^2],1] && NeQ[Coeff[Px,x^2,0],0]



